version: "3.9"

services:
  # ==============================
  # Backend Express.js
  # ==============================
  backend:
    build: .
    container_name: backend-express
    restart: always
    env_file:
      - .env
    environment:
      - DATABASE_URL=mysql://root:password@db:3306/opak_kopi
      - PORT=3000
    ports:
      - "3000:3000"
    depends_on:
      - db

  # ==============================
  # MySQL Database
  # ==============================
  db:
    image: mysql:8.1
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: opak_kopi
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  # ==============================
  # phpMyAdmin
  # ==============================
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    depends_on:
      - db
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "8080:80"

# ==============================
# Volume untuk menyimpan data MySQL
# ==============================
volumes:
  db_data:
